### ISSUE TITLE
How to validate checkboxs selection count?

### ISSUE THREAD

**Issue by wpok** [rickharrison/validate.js#123]
Example: I have 5 checkboxs, and the maximum / minimum / exactly selection count is 3. How can I validate this rule? 

And is it possible to validate checkboxs selection count when a checkbox is clicked?

Thanks!

**Comment by ThibWeb** [comment]
Hi there,

for future reference, here's an example of such a custom parameterized rule to validate only if more than X / less than X / exactly X checkboxes are checked:

~~~javascript
var rules = [
   {
      name: 'my_checkboxes',
      rules: 'required|callback_multiple_checked[2]'
    },
];

  // Validate that multiple checkboxes are checked.
  validator.registerCallback('multiple_checked', function(_, nbToCheck, validator) {
    var nbChecked = $('[name=' + validator.name + ']').reduce(function (acc, elt) {
      acc += $(elt).is(':checked') ? 1 : 0;
      return acc;
    }, 0);

    return nbChecked >= nbToCheck;
  });
~~~

This example uses Zepto for DOM manipulations, and validates if there are more than X checked checkboxes. It shouldn't be hard to port to DOM APIs / jQuery, or to change the last line to have "less than / equal number" validations.

Cheers!
