### ISSUE TITLE
Email Validation validate.js

### ISSUE THREAD

**Issue by MonkWizard** [rickharrison/validate.js#133]
Hi Rick

I have just implemented your form validation and during testing it didn't validate emails correctly and is let emails though without the TLD specified i.e. aaaa@aaaa.

**Comment by rickharrison** [comment]
The regex is from the HTML5 spec: https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address

If you want a more restrictive regex, you can use a custom rule.
