### ISSUE TITLE
Doesn't call custom validators

### ISSUE THREAD

**Issue by hassankhan** [rickharrison/validate.js#134]
Can't seem to get custom validation rules to work no matter what. Any help appreciated, thanks!

**Comment by rickharrison** [comment]
Could you please post the code you have?

**Comment by hassankhan** [comment]
Hi, sorry, I can't seem to reproduce with a smaller example, and the actual code's on my office machine.

**Comment by hassankhan** [comment]
Actually, the problem seems to be #74, here's a [jsFiddle](http://jsfiddle.net/d6wjf37g/)
