### ISSUE TITLE
email and url regular expressions fail to match 

### ISSUE THREAD

**Issue by abedurftig** [rickharrison/validate.js#137]
Hello Rick

Great library. I am actually building my own little library based on validate.js. I noticed that two regular expression do not match when they should:

emailRegex does not match ‘email@com’, 
urlRegex does not match ‘http://homepagecom’

I have cloned the repository and created a branch with a fix, thought I could just send you a pull request. But my GitHub client tells me that the authentication failed. So is it not that easy?

**Comment by rickharrison** [comment]
Perhaps try opening the PR on github.com
