### ISSUE TITLE
Show error messages next to fields

### ISSUE THREAD

**Issue by garygreen** [rickharrison/validate.js#142]
Is there an example of how to do this (assume it's not a built in feature?).

**Comment by rickharrison** [comment]
It is not currently a built in feature. You would need to look at the errors in the callback and display them in the right spot using any dom manipulation you have.

**Comment by yousefcisco** [comment]
I think there's still something to be done here to make this kind of functionality easier to build. Currently we're passing down the element id and name in the errors object. If we pass over the actual element as well then it would improve the performance of any custom functionality the we build for this, saves us having to lookup the element all over again.

If this is something you'd be interested in having then I can create a PR for it.

**Comment by garygreen** [comment]
@yousefcisco I agree, though this library seems to be soley for validating and doesn't really care so much about the UI.

I've actually recently created a validator based on bootstrap called [dominar.js](https://github.com/garygreen/dominar) it might be of interest to you :-)

**Comment by yousefcisco** [comment]
@garygreen Yes but I actually really like that and thing it's a feature. The clients that we work with require complex solutions for everything and we've struggled with other validation plugins in the past because they had lots of ideas on how the UI should look and behave.

**Comment by garygreen** [comment]
@yousefcisco totally agree which is why I made [dominar.js](https://github.com/garygreen/dominar). It's very flexible in it's options and uses a bootstrap-style format for containing and highlighting error messages (it would be good to support other UI frameworks in the future) but even now it's pretty generic and you can configure placement of errors, custom error messages, it's all pretty generic.

**Comment by rickharrison** [comment]
@yousefcisco Yes, a PR to help iterate towards this feature would be greatly appreciated.

**Comment by yousefcisco** [comment]
@rickharrison cool, I'll try and get something together

**Comment by yousefcisco** [comment]
@rickharrison I just took a look at the code and it seems the element is being passed back in the errors object which should make things easy to build this functionality. Is this something you want rolled into the plugin itself?

**Comment by rickharrison** [comment]
My goal is to keep the library as small as possible. So I'm open to ways to accomplish it in library, or perhaps maybe just a guide to describe how to accomplish it with the current API.

**Comment by yousefcisco** [comment]
I think a guide would probably be the best way to go about it without bloating the library too much.

**Comment by garygreen** [comment]
Well I've created [dominar.js](https://github.com/garygreen/dominar) which does all this stuff, pretty customisable so closing for now :smiley_cat:
