### ISSUE TITLE
Validate rules on element

### ISSUE THREAD

**Issue by garygreen** [rickharrison/validate.js#143]
Maybe it would be quite cool to have an optional plugin that can read and parse validation rules in-line with the element, to avoid having to dig into js to add validation? It's especially useful when using HTML 5 / built in browser validation rules on the elements.

``` html
<!-- {name: "some_num", rules: "integer|min[5]|max[10]|numeric_step[2]" } -->
<input type="number" min="5" max="10" step="2" name="some_num"/>

<!-- {name: "my_email", rules: "required|valid_email" } -->
<input type="email" name="my_email" required>

<textarea data-validate="alpha">
```

**Comment by rickharrison** [comment]
Yea, I would definitely like to support something like this, most likely using a `data-*` attribute.
