### ISSUE TITLE
Form submits when form is not successful validated

### ISSUE THREAD

**Issue by kabouter** [rickharrison/validate.js#157]
I have a problem when I fill in my form and the validation is not successful that the form is still submitted.
I thought the form doesn't submit when the validation fails.

Am I doing something wrong or how can I solve this.

This my form:	
https://goo.gl/TWKii1

**Comment by rickharrison** [comment]
I just want there and the form does not submit. Please make sure you do not have any errors being printed in your console.

**Comment by kabouter** [comment]
I see a post request to my server that fails in Firefox and Opera console. This post request failed because the submitted data don't meet the server side requirements. This not fails because of the client side validation!

If you fill in the date and time in my form you will get a 202 response and the data is submitted even if the client validation fails.

**Comment by rickharrison** [comment]
The default behavior is to prevent the form submission as can be seen here: http://rickharrison.github.io/validate.js/

If it is submitting, it is because of an error somewhere in your code.
