### ISSUE TITLE
Error in email regex

### ISSUE THREAD

**Issue by madvik** [rickharrison/validate.js#168]
The email regex, line 58 is not correct for australian email like : thing@thing.com.au

**Comment by madvik** [comment]
http://output.jsbin.com/ozeyag/19

**Comment by rickharrison** [comment]
It works on this page: http://rickharrison.github.io/validate.js/

I think you are using a custom email regex that might not be working.

**Comment by madvik** [comment]
Oh sorry, it's a mistak, I don't understand.However I test on your demo website.

**Comment by madvik** [comment]
I understand, an error appear when I paste the email a space is add at the end: "hgigih@machinmail.com.au " 
A trim() is not appy on the string.
