### ISSUE TITLE
email regex

### ISSUE THREAD

**Issue by ncou** [rickharrison/validate.js#170]
Hi,

Is it possible to change the regex with this one :

emailRegex = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,

Because with the existing regex, the email "test@test" is interpreted as OK, but it's not a valid adress.

Thank you.

**Comment by rickharrison** [comment]
The email regex being used is from https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address. If you need a stricter rule, you should use a custom validator.
