### ISSUE TITLE
Form submitted despite errors with Asp.net Ajax.BeginForm

### ISSUE THREAD

**Issue by GeeWizWow** [rickharrison/validate.js#172]
The Form was being submitted despite errors when using asp .net's Ajax.BeginForm.

Was occurring in both chrome and I.E 11 so I assume the browser wasn't to blame.
Fixed it by adding ```evt.stopImmediatePropagation();``` after ```evt.preventDefault()``` on line ~264

**Comment by rickharrison** [comment]
We cannot guarantee any interoperability with platforms like asp.
