### ISSUE TITLE
Custom Validation Rules - Not seem to be working?

### ISSUE THREAD

**Issue by dvLden** [rickharrison/validate.js#175]
```
const CONTACT_FORM = document.querySelector('#FormContact');

var validator = new FormValidator(CONTACT_FORM, [{
    name: 'contact-name',
    rules: 'required|valid_name'
}, {
    name: 'contact-email',
    rules: 'required|valid_email'
}, {
    name: 'contact-subject',
    rules: 'required'
}, {
    name: 'contact-message',
    rules: 'required|min_length[50]|max_length[500]'
}], function(errors, event) {
    if (errors.length > 0) {
        console.log(errors);
    }
});

validator
    .registerCallback('valid_name', value => /^[a-zA-Z ]{2,30}$/.test(value))
    .setMessage('valid_name', 'Please enter your full name.');
```

As it seem to me, it does not pick up custom validation rule. I tried hardcoding to always `return false` and still it passes like it is truthy...

```
validator
    .registerCallback('valid_name', () => false)
    .setMessage('valid_name', "You can't pass this rule.");
```

Oh and there's one more thing. The `contact-subject` has a rule set to `required` which is `select element` having disabled and selected default value, so I assume the expectation of validator is to say that field is not valid since it is pending non-disabled selection, right?

**Comment by rickharrison** [comment]
In the `FormValidator` definition, the rule needs to be `callback_valid_name` like this:

```
rules: 'required|callback_valid_name'
```

You can read more about custom rules here: http://rickharrison.github.io/validate.js/
