### ISSUE TITLE
Grouped inputs ([]) for PHP Arrays not being validated.

### ISSUE THREAD

**Issue by bingocaller** [rickharrison/validate.js#74]
I have a form with some grouped input fields, which have a set of square brackets at the end of their names like so:

``` html
<input name="query_519535_2_0_0[]" id="query_519535_2_0_0_1" value="1" type="radio">
<input name="query_519535_2_0_0[]" id="query_519535_2_0_0_2" value="2" type="radio">
<input name="query_519535_2_0_0[]" id="query_519535_2_0_0_3" value="3" type="radio">
```

When I try to validate these groups of inputs like so:

``` javascript
var validationRules = [
        {name: 'query_519535_2_0_0[]', rules: 'required'}
    ];
```

hoping to validate whether any of the radio buttons have been selected, but nothing happens on submit. I have other inputs with no brackets in their names that are being validated as expected.

I tried removing the brackets from the JS but this resulted in the radio groups evaluating to false no matter what.

**Comment by hassankhan** [comment]
I'm seeing this issue again: http://jsfiddle.net/jgx32bs6/
